package com.gorkem.vehicle_inspector.entity;

public enum VehiclePart {
    UNKNOWN,
    FRONT_BUMPER,
    REAR_BUMPER,
    HOOD,
    ROOF,
    TRUNK,
    FRONT_LEFT_DOOR,
    FRONT_RIGHT_DOOR,
    REAR_LEFT_DOOR,
    REAR_RIGHT_DOOR,
    FRONT_LEFT_FENDER,
    FRONT_RIGHT_FENDER,
    REAR_LEFT_FENDER,
    REAR_RIGHT_FENDER,
    WINDSHIELD,
    REAR_WINDSHIELD,
    FRONT_LEFT_HEADLIGHT,
    FRONT_RIGHT_HEADLIGHT,
    REAR_LEFT_TAILLIGHT,
    REAR_RIGHT_TAILLIGHT,
    LEFT_SIDE_MIRROR,
    RIGHT_SIDE_MIRROR
}